name: Update README with Performance Test Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual execution

jobs:
  run-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20] # Run on multiple Node.js versions

    name: Run and Update README on Node.js ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install # Skip if no dependencies are needed

      - name: Run JavaScript loop performance test and save output
        run: node test-loops.js > performance-results-${{ matrix.node-version }}.txt

      - name: Save results for later use
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance-results-${{ matrix.node-version }}.txt

  update-readme:
    runs-on: ubuntu-latest
    needs: run-js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all test results
        uses: actions/download-artifact@v3
        with:
          name: performance-results

      - name: Generate Markdown table for README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## JavaScript Loop Performance Test Results" > README.md
          echo "### The code is all AI generated" > README.md
          echo "" >> README.md
          echo "| Node.js Version | for | for...in | for...of | forEach | while | do...while | map | filter | reduce |" >> README.md
          echo "|----------------|-----|---------|--------|--------|-------|----------|-----|--------|--------|" >> README.md

          for version in 16 18 20; do
            results=$(cat performance-results-$version.txt | awk '{print $NF}')
            echo "| $version | $results |" >> README.md
          done

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          
          # Check if there are any changes
          if git diff --staged --quiet; then
            echo "No changes to commit. Exiting..."
            exit 0
          fi
          
          git commit -m "Update README with latest loop performance results [skip ci]"
          git push
