name: Update README with Performance Test Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20] # Run on multiple Node.js versions

    name: Run and Update README on Node.js ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install # If dependencies are needed

      - name: Run JavaScript loop performance test and save output
        run: node index.js > performance-results.txt

      - name: Update README with new performance results
        run: |
          echo "## JavaScript Loop Performance Test Results" > README.md
          echo "### Node.js version: ${{ matrix.node-version }}" >> README.md
          cat performance-results.txt >> README.md
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with latest loop performance results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
